import type { AppError, AppErrorCode } from "./errors";
import { classifyError } from "./errors";

export interface InstallResult {
  success: boolean;
  error: string | null;
  base_files_copied: number;
  extras_files_copied: number;
  extras_warning: string | null;
  rom_dirs_created: number;
}

export type InstallError = AppError;
export type InstallErrorCode = AppErrorCode;

export type InstallResultEither =
  | { success: true; data: InstallResult }
  | { success: false; error: InstallError };

export type InstallPhase =
  | "idle"
  | "downloading"
  | "extracting"
  | "copying"
  | "complete"
  | "error";

export interface InstallProgressEvent {
  step: string;
  details: string;
  /** Optional byte-level download progress (set when `step === "download"`). */
  currentBytes?: number;
  /** Optional total bytes (None when server didn't send Content-Length). */
  totalBytes?: number | null;
  /** Stable identifier for React keys; generated by the consumer when appending to a log. */
  id?: string;
}

/**
 * UI install state for a single package. Shared between PackageStore
 * (which owns the map of states) and PackageCard (which renders one).
 * Kept here as the single source of truth so the store and the card
 * stay in lock-step.
 */
export type InstallStatus = "idle" | "installing" | "done" | "error";

export interface PackageInstallState {
  status: InstallStatus;
  error?: string;
}

export async function installMinui(options: {
  baseUrl: string;
  extrasUrl?: string;
  baseChecksum?: string;
  extrasChecksum?: string;
  sdMount: string;
  platform: string;
  extrasPlatform: string;
  version: string;
  forkName?: string;
}): Promise<InstallResultEither> {
  try {
    const { invoke } = await import("@tauri-apps/api/core");
    const result = await invoke<InstallResult>("install_minui", {
      baseUrl: options.baseUrl,
      extrasUrl: options.extrasUrl || null,
      baseChecksum: options.baseChecksum || null,
      extrasChecksum: options.extrasChecksum || null,
      sdMount: options.sdMount,
      platform: options.platform,
      extrasPlatform: options.extrasPlatform,
      version: options.version,
      forkName: options.forkName || null,
    });

    if (result.success) {
      return { success: true, data: result };
    }

    const errorMsg = result.error || "Installation failed";
    const code = classifyError(errorMsg);

    return {
      success: false,
      error: { message: errorMsg, code },
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    return {
      success: false,
      error: { message, code: "UNKNOWN_ERROR" },
    };
  }
}

/**
 * Start a cancellable install. The Rust backend spawns the install in a
 * background task and emits `install-complete` / `install-error` events
 * when done. Call `cancelInstall()` to abort mid-flight.
 */
export async function startInstall(options: {
  baseUrl: string;
  extrasUrl?: string;
  baseChecksum?: string;
  extrasChecksum?: string;
  sdMount: string;
  platform: string;
  extrasPlatform: string;
  version: string;
  forkName?: string;
}): Promise<string> {
  const { invoke } = await import("@tauri-apps/api/core");
  return await invoke<string>("start_install", {
    baseUrl: options.baseUrl,
    extrasUrl: options.extrasUrl || null,
    baseChecksum: options.baseChecksum || null,
    extrasChecksum: options.extrasChecksum || null,
    sdMount: options.sdMount,
    platform: options.platform,
    extrasPlatform: options.extrasPlatform,
    version: options.version,
    forkName: options.forkName || null,
  });
}

/**
 * Start a cancellable install and wait for the result via Tauri events.
 *
 * Calls `startInstall()` (fire-and-forget), then listens for the
 * `install-complete` or `install-error` event and resolves/rejects
 * the returned promise. Progress events are emitted separately and
 * handled by the caller's `install-progress` listener.
 */
export async function startInstallAndWait(options: {
  baseUrl: string;
  extrasUrl?: string;
  baseChecksum?: string;
  extrasChecksum?: string;
  sdMount: string;
  platform: string;
  extrasPlatform: string;
  version: string;
  forkName?: string;
}): Promise<InstallResult> {
  const { listen } = await import("@tauri-apps/api/event");

  return new Promise<InstallResult>((resolve, reject) => {
    const unlistens: (() => void)[] = [];

    const cleanup = () => {
      for (const u of unlistens) u();
    };

    // Attach listeners BEFORE starting the install to avoid
    // a race where the event fires before we subscribe.
    listen<InstallResult>("install-complete", (event) => {
      cleanup();
      resolve(event.payload);
    })
      .then((completeUnlisten) => {
        unlistens.push(completeUnlisten);
        return listen<string>("install-error", (event) => {
          cleanup();
          reject(new Error(event.payload));
        });
      })
      .then((errorUnlisten) => {
        unlistens.push(errorUnlisten);
        return startInstall(options);
      })
      .catch((err) => {
        cleanup();
        reject(err);
      });
  });
}

/**
 * Cancel the in-flight install, if any. No-op when no install is running.
 */
export async function cancelInstall(): Promise<void> {
  const { invoke } = await import("@tauri-apps/api/core");
  await invoke("cancel_install");
}
